name: ventoptima
description: "App til energioptimering af ventilationsanlæg"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.7.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.18.1
  image_picker: ^1.0.4   # ← tilføjet for at understøtte billedtagning

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/bravida_logo_rgb_pos.png
    - assets/images/morville_logo.png
    - assets/images/star_logo.png
    - assets/images/ebmpapst.png
    - assets/images/novenco.png
    - assets/images/ziehlabegg.png